### ISSUE TITLE
Data-binding between ember and polymer is awkward at best.

### ISSUE THREAD

**Issue by pdesjardins90** [dunnkers/ember-polymer#28]
Consider this simple login form component template:
```html
<!-- templates/components/login-form.hbs -->

<paper-card heading="Sign in to your account">
  <div class="card-content">
    <paper-input id="username-field" label="Email" value="{{username}}"></paper-input>
    <paper-input id="password-field" label="Password" type="password" value="{{password}}"></paper-input>
    <paper-button raised {{action 'authenticate'}}>Sign in</paper-button>
  </div>
</paper-card>
```

And its assorted ember.js component:

```javascript
// components/login-form.js
import Ember from 'ember';

export default Ember.Component.extend({
  session: Ember.inject.service('session'),

  actions: {
    authenticate() {
      let { username, password } = this.getProperties('username', 'password');
      this.get('session').authenticate('authenticator:oauth2-password-grant', username, password)
        .catch((failure) => {
          console.log(failure.error);
        });
    }
  }
});
```

The {{username}} and {{password}} values are loaded when the page renders, but they are not updated when the user changes the text field values. If I understood this correctly, it's due to the fact that ember evaluates curly braces helpers before polymer evaluates them. I'm not sure I understand perfectly all the mechanisms involved in there yet, but still I found a workaround for the time being: adding event listeners on defined paper-input events after ember renders the view:

```javascript
// components/login-form.js
  didInsertElement: function() {
    let self = this;

    document
      .getElementById('username-field')
      .addEventListener('change', function() {
        self.set('username', this.value);
      });

    document
      .getElementById('password-field')
      .addEventListener('change', function() {
        self.set('password', this.value);
      });
  }
```

Also, I tried using polymer one-way data binding notation [[ ]] but it wasn't evaluated either... 

If anyone can come up with suggestions on how best we should fix this problem, please share! Thanks

**Comment by dunnkers** [comment]
The two data binding systems indeed do not go well together. When the value of an attribute changes, Polymer elements notify using dom events that only Polymer's data binding system understands. The bound ember value is not updated.

So, in order to fix this, we have to manually listen for change and update the bound value (or send a change action to conform to the Data Down Actions Up principle). The workaround you gave is indeed the way to solve this.

I have been working on another addon which gives you the bindings, [ember-polymer-paper](https://github.com/dunnkers/ember-polymer-paper). The addon wraps paper elements in Ember components and adds event listeners in order to bind values. It's not quite finished yet, but I hope on releasing it soon. It is usable just fine already though! Just npm install it with the github link it if you wanna use it already. If you wanna help a hand, take a look at the issues.

In order to add a little bit more clarity over how binding should be done with Polymer elements, I'll add a little note in the README. And @pdesjardins90 thanks for opening the issue, all contributions are very much appreciated.
